#!/bin/bash
set -e # fail on any error
set -u # treat unset variables as errors

# ======[ Trap Errors ]======#
set -E # let shell functions inherit ERR trap

# Trap non-normal exit signals:
# 1/HUP, 2/INT, 3/QUIT, 15/TERM, ERR
trap err_handler 1 2 3 15 ERR
function err_handler {
local exit_status=${1:-$?}
logger -s -p "syslog.err" -t "FIREWALL-TESTER" "firewall-tester.deb script '$0' error code $exit_status (line $BASH_LINENO: '$BASH_COMMAND')"
exit $exit_status
}

etcfld="/etc/firewall-tester"
usrbin="/usr/bin/firewall-tester"
hookfld="/usr/share/firewall-tester"
docfld="/usr/share/doc/firewall-tester"
man1="/usr/share/man/man1/firewall-tester.1.gz"
man1ru="/usr/share/man/ru/man1/firewall-tester.1.gz"
cron="/etc/cron.daily/firewall-tester"
lr="/etc/logrotate.d/firewall-tester"

rm -rf $etcfld
rm -rf $usrbin
rm -rf $hookfld
rm -rf $docfld
rm -rf $man1
rm -rf $man1ru
rm -rf $cron
rm -rf $lr
rm -rf /var/log/firewall.scan.log

echo "uninstalled."

exit 0
